name: Bug Report
description: Create a bug report to help us improve.
title: "[BUG] - "
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the following template to help us understand the issue and work towards a solution.

  - type: input
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: "Describe the bug here..."

  - type: input
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: A step-by-step list of how to reproduce the bug.
      placeholder: "1. Go to '...'\n2. Click on '...'\n3. Scroll down to '...'\n4. See error"

  - type: input
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: "Describe what you expected to happen..."

  - type: input
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: "Describe what actually happened..."

  - type: input
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain your problem.
    validations:
      required: true