import { db, Product, Review } from 'astro:db';

export default async function seed() {
  await db.insert(Product).values([
    { id: 1, name: 'Ethiopian Yirgacheffe', slug: 'ethiopian-yirgacheffe', description: 'Bright and fruity with wine-like acidity.', price: 18.99, roast: 'Light', origin: 'Ethiopia', notes: 'Blueberry, citrus, floral' },
    { id: 2, name: 'Colombian Supremo', slug: 'colombian-supremo', description: 'Perfectly balanced with nutty sweetness.', price: 16.99, roast: 'Medium', origin: 'Colombia', notes: 'Caramel, walnut, mild citrus' },
    { id: 3, name: 'Sumatra Mandheling', slug: 'sumatra-mandheling', description: 'Full-bodied and earthy.', price: 17.99, roast: 'Dark', origin: 'Indonesia', notes: 'Earthy, herbal, dark chocolate' },
    { id: 4, name: 'Sunrise Blend', slug: 'sunrise-blend', description: 'Our signature morning blend.', price: 15.99, roast: 'Medium', origin: 'Blend', notes: 'Caramel, orange, chocolate' },
    { id: 5, name: 'Guatemala Antigua', slug: 'guatemala-antigua', description: 'Complex and spicy with a velvety body.', price: 17.49, roast: 'Medium', origin: 'Guatemala', notes: 'Cocoa, spice, brown sugar' },
    { id: 6, name: 'Kenya AA', slug: 'kenya-aa', description: 'Bold and bright with a grapefruit kick.', price: 19.99, roast: 'Light', origin: 'Kenya', notes: 'Grapefruit, blackcurrant, sugar cane' },
    { id: 7, name: 'Costa Rica Tarrazú', slug: 'costa-rica-tarrazu', description: 'Clean and sweet with a honey finish.', price: 18.49, roast: 'Medium', origin: 'Costa Rica', notes: 'Honey, almond, citrus' },
    { id: 8, name: 'Brazil Santos', slug: 'brazil-santos', description: 'Smooth and low-acid with chocolate notes.', price: 14.99, roast: 'Medium', origin: 'Brazil', notes: 'Chocolate, peanut, mild fruit' },
    { id: 9, name: 'Espresso Roast', slug: 'espresso-roast', description: 'Rich and bold, built for espresso.', price: 16.49, roast: 'Dark', origin: 'Blend', notes: 'Dark chocolate, toasted walnut, caramel' },
    { id: 10, name: 'Decaf House Blend', slug: 'decaf-house-blend', description: 'All the flavor, none of the buzz.', price: 15.49, roast: 'Medium', origin: 'Blend', notes: 'Milk chocolate, hazelnut, soft berry' },
    { id: 11, name: 'Papua New Guinea', slug: 'papua-new-guinea', description: 'Exotic and complex with tropical notes.', price: 19.49, roast: 'Medium', origin: 'Papua New Guinea', notes: 'Mango, brown sugar, butter' },
    { id: 12, name: 'Rwanda Kivu', slug: 'rwanda-kivu', description: 'Sweet and delicate with floral aroma.', price: 18.99, roast: 'Light', origin: 'Rwanda', notes: 'Red grape, jasmine, caramel' },
    { id: 13, name: 'Mexican Chiapas', slug: 'mexican-chiapas', description: 'Bright and nutty with a clean finish.', price: 15.99, roast: 'Medium', origin: 'Mexico', notes: 'Almond, green apple, toffee' },
    { id: 14, name: 'French Roast', slug: 'french-roast', description: 'Smoky and intense for dark roast lovers.', price: 16.99, roast: 'Dark', origin: 'Blend', notes: 'Smoke, dark cocoa, roasted marshmallow' },
    { id: 15, name: 'Honduran Marcala', slug: 'honduran-marcala', description: 'Silky body with tropical sweetness.', price: 16.49, roast: 'Medium', origin: 'Honduras', notes: 'Peach, vanilla, milk chocolate' },
    { id: 16, name: 'Tanzanian Peaberry', slug: 'tanzanian-peaberry', description: 'Vibrant and juicy with a wine-like finish.', price: 20.99, roast: 'Light', origin: 'Tanzania', notes: 'Blackberry, lemon zest, brown sugar' },
    { id: 17, name: 'Italian Roast', slug: 'italian-roast', description: 'Deep and bold with a bittersweet edge.', price: 17.49, roast: 'Dark', origin: 'Blend', notes: 'Charred oak, espresso, anise' },
    { id: 18, name: 'Peru Cajamarca', slug: 'peru-cajamarca', description: 'Balanced and mild with nutty undertones.', price: 16.99, roast: 'Medium', origin: 'Peru', notes: 'Cashew, milk chocolate, dried fig' },
    { id: 19, name: 'Midnight Blend', slug: 'midnight-blend', description: 'Our darkest roast for the bold at heart.', price: 17.99, roast: 'Dark', origin: 'Blend', notes: 'Molasses, black cherry, smoky cedar' },
    { id: 20, name: 'Hawaiian Kona', slug: 'hawaiian-kona', description: 'Rare and luxurious with buttery sweetness.', price: 34.99, roast: 'Medium', origin: 'Hawaii', notes: 'Butter, macadamia, brown sugar' },
    { id: 21, name: 'Jamaican Blue Mountain', slug: 'jamaican-blue-mountain', description: 'Exceptionally smooth with zero bitterness.', price: 39.99, roast: 'Medium', origin: 'Jamaica', notes: 'Floral, sweet herb, creamy chocolate' },
    { id: 22, name: 'Vietnamese Robusta', slug: 'vietnamese-robusta', description: 'Strong and punchy, perfect for iced coffee.', price: 13.99, roast: 'Dark', origin: 'Vietnam', notes: 'Dark chocolate, whiskey, burnt caramel' },
    { id: 23, name: 'Burundi Kayanza', slug: 'burundi-kayanza', description: 'Delicate acidity with a silky mouthfeel.', price: 19.49, roast: 'Light', origin: 'Burundi', notes: 'Lemon, black tea, raw honey' },
    { id: 24, name: 'Indian Monsooned Malabar', slug: 'indian-monsooned-malabar', description: 'Uniquely mellow from monsoon processing.', price: 18.49, roast: 'Medium', origin: 'India', notes: 'Tobacco, clove, bittersweet chocolate' },
    { id: 25, name: 'Mocha Java Blend', slug: 'mocha-java-blend', description: 'The original coffee blend, rich and complex.', price: 17.99, roast: 'Medium', origin: 'Blend', notes: 'Wine, chocolate, spice' },
    { id: 26, name: 'Nicaragua Jinotega', slug: 'nicaragua-jinotega', description: 'Creamy and sweet with a citrus lift.', price: 16.49, roast: 'Medium', origin: 'Nicaragua', notes: 'Orange cream, toffee, walnut' },
    { id: 27, name: 'Congo Kivu', slug: 'congo-kivu', description: 'Bold and earthy with a wild character.', price: 18.99, roast: 'Dark', origin: 'Congo', notes: 'Dark plum, cedar, roasted peanut' },
    { id: 28, name: 'Breakfast Blend', slug: 'breakfast-blend', description: 'Light and approachable, an everyday favorite.', price: 14.49, roast: 'Light', origin: 'Blend', notes: 'Citrus, toast, mild berry' },
    { id: 29, name: 'Yunnan China', slug: 'yunnan-china', description: 'Surprisingly sweet with a tea-like quality.', price: 17.99, roast: 'Light', origin: 'China', notes: 'Rose, dark chocolate, plum' },
    { id: 30, name: 'El Salvador Pacamara', slug: 'el-salvador-pacamara', description: 'Juicy and complex, a specialty standout.', price: 21.99, roast: 'Light', origin: 'El Salvador', notes: 'Tropical fruit, jasmine, honeycomb' },
  ]);

  await db.insert(Review).values([
    { id: 1, productSlug: 'brazil-santos', author: 'Maria S.', rating: 5, comment: 'So smooth and easy to drink. Perfect everyday coffee.' },
    { id: 2, productSlug: 'brazil-santos', author: 'James K.', rating: 4, comment: 'Low acidity and great chocolate notes. Love it.' },
    { id: 3, productSlug: 'breakfast-blend', author: 'Sarah L.', rating: 5, comment: 'Light and approachable. My go-to morning cup.' },
    { id: 4, productSlug: 'breakfast-blend', author: 'Tom R.', rating: 4, comment: 'Great citrus notes. Works perfectly iced too.' },
    { id: 5, productSlug: 'burundi-kayanza', author: 'Alex P.', rating: 5, comment: 'Delicate and complex. The honey sweetness is lovely.' },
    { id: 6, productSlug: 'burundi-kayanza', author: 'Rachel M.', rating: 4, comment: 'Beautiful lemon and black tea flavors. So unique.' },
    { id: 7, productSlug: 'colombian-supremo', author: 'Chris D.', rating: 4, comment: 'Perfectly balanced. Great for everyday drinking.' },
    { id: 8, productSlug: 'colombian-supremo', author: 'Emily W.', rating: 3, comment: 'Smooth and nutty. My go-to office coffee.' },
    { id: 9, productSlug: 'ethiopian-yirgacheffe', author: 'Lina T.', rating: 5, comment: 'Incredible blueberry notes. Best light roast I have tried.' },
    { id: 10, productSlug: 'ethiopian-yirgacheffe', author: 'Derek H.', rating: 4, comment: 'Bright and fruity. A truly special coffee.' },
    { id: 11, productSlug: 'sumatra-mandheling', author: 'Karen F.', rating: 4, comment: 'Earthy and bold. Perfect for a cold morning.' },
    { id: 12, productSlug: 'sumatra-mandheling', author: 'Paul N.', rating: 3, comment: 'Rich dark chocolate flavor but a bit heavy for me.' },
    { id: 13, productSlug: 'sunrise-blend', author: 'Megan C.', rating: 5, comment: 'My absolute favorite morning coffee. So well balanced.' },
    { id: 14, productSlug: 'sunrise-blend', author: 'Brian J.', rating: 4, comment: 'Love the caramel and orange notes. Great daily brew.' },
    { id: 15, productSlug: 'guatemala-antigua', author: 'Sofia R.', rating: 4, comment: 'Complex and spicy. Wonderful with a splash of cream.' },
    { id: 16, productSlug: 'guatemala-antigua', author: 'Nathan B.', rating: 5, comment: 'One of the best medium roasts out there. Love it.' },
    { id: 17, productSlug: 'kenya-aa', author: 'Olivia M.', rating: 5, comment: 'Bold and bright. The grapefruit kick is amazing.' },
    { id: 18, productSlug: 'kenya-aa', author: 'Ryan G.', rating: 5, comment: 'Exceptional quality. Worth every penny.' },
    { id: 19, productSlug: 'costa-rica-tarrazu', author: 'Hannah L.', rating: 4, comment: 'Clean and sweet. The honey finish is delightful.' },
    { id: 20, productSlug: 'costa-rica-tarrazu', author: 'Marcus W.', rating: 4, comment: 'Perfectly balanced with lovely almond notes.' },
    { id: 21, productSlug: 'espresso-roast', author: 'Julia A.', rating: 5, comment: 'Makes the best espresso at home. Rich and bold.' },
    { id: 22, productSlug: 'espresso-roast', author: 'Vincent P.', rating: 4, comment: 'Great crema and deep caramel sweetness.' },
    { id: 23, productSlug: 'decaf-house-blend', author: 'Linda K.', rating: 3, comment: 'Decent for decaf. Nice hazelnut flavor.' },
    { id: 24, productSlug: 'decaf-house-blend', author: 'George S.', rating: 4, comment: 'Finally a decaf that actually tastes good.' },
    { id: 25, productSlug: 'papua-new-guinea', author: 'Ava T.', rating: 4, comment: 'Exotic and interesting. The mango note is surprising.' },
    { id: 26, productSlug: 'papua-new-guinea', author: 'Daniel R.', rating: 5, comment: 'Unique and complex. A real conversation starter.' },
    { id: 27, productSlug: 'rwanda-kivu', author: 'Emma J.', rating: 5, comment: 'Delicate and floral. Absolutely beautiful coffee.' },
    { id: 28, productSlug: 'rwanda-kivu', author: 'Sam C.', rating: 4, comment: 'Sweet with lovely jasmine aroma. Very elegant.' },
    { id: 29, productSlug: 'mexican-chiapas', author: 'Chloe D.', rating: 3, comment: 'Bright and nutty. A solid everyday option.' },
    { id: 30, productSlug: 'mexican-chiapas', author: 'Tyler M.', rating: 4, comment: 'Clean finish with nice toffee sweetness.' },
    { id: 31, productSlug: 'french-roast', author: 'Nick B.', rating: 4, comment: 'Smoky and intense. Great for French press.' },
    { id: 32, productSlug: 'french-roast', author: 'Diana L.', rating: 3, comment: 'Bold and dark. A little too smoky for daily use.' },
    { id: 33, productSlug: 'honduran-marcala', author: 'Isabelle F.', rating: 5, comment: 'Silky smooth with amazing peach notes. A hidden gem.' },
    { id: 34, productSlug: 'honduran-marcala', author: 'Kevin H.', rating: 4, comment: 'Sweet and creamy. One of my new favorites.' },
    { id: 35, productSlug: 'tanzanian-peaberry', author: 'Zoe W.', rating: 5, comment: 'Juicy and vibrant. The blackberry flavor is incredible.' },
    { id: 36, productSlug: 'tanzanian-peaberry', author: 'Matt E.', rating: 5, comment: 'Best peaberry I have ever had. Worth the price.' },
    { id: 37, productSlug: 'italian-roast', author: 'Grace P.', rating: 3, comment: 'Deep and bold. Good for espresso-based drinks.' },
    { id: 38, productSlug: 'italian-roast', author: 'Leo V.', rating: 4, comment: 'Strong bittersweet edge. Pairs well with dessert.' },
    { id: 39, productSlug: 'peru-cajamarca', author: 'Nora S.', rating: 4, comment: 'Mild and balanced. The fig note is a nice touch.' },
    { id: 40, productSlug: 'peru-cajamarca', author: 'Oscar T.', rating: 4, comment: 'Smooth and nutty. Great value for the quality.' },
    { id: 41, productSlug: 'midnight-blend', author: 'Ruby K.', rating: 4, comment: 'Dark and mysterious. Love the black cherry flavor.' },
    { id: 42, productSlug: 'midnight-blend', author: 'Ian D.', rating: 3, comment: 'Bold and smoky. A good after-dinner coffee.' },
    { id: 43, productSlug: 'hawaiian-kona', author: 'Stella M.', rating: 5, comment: 'Luxurious and buttery. An absolute treat.' },
    { id: 44, productSlug: 'hawaiian-kona', author: 'Jack R.', rating: 5, comment: 'Worth the splurge. Incredibly smooth and sweet.' },
  ]);
}
